[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
StippleWaferPlot = "29f11006-3202-4091-a17b-0a26282d76dd"

[Genie]
instantiated_pwd = "/Users/pere/genie/webinars/asml/waferPluginDemo"
